# Use a base image with JDK and Maven to build the application
FROM maven:3.8.4-openjdk-17-slim AS builder

# Set the working directory in the container
WORKDIR /Kafka-Backend

# Copy the Maven project file and download the dependencies
COPY pom.xml .
RUN mvn -B dependency:go-offline

# Copy the application source code
COPY . .

# Build the application
RUN mvn -B package -DskipTests

# Use a lightweight base image with JRE to run the application
FROM adoptopenjdk:17-jre-hotspot

# Set the working directory in the container
WORKDIR /Kafka-Backend

# Copy the built JAR file from the builder stage
COPY --from=builder /app/target/Kafka-Backend.jar ./Kafka-Backend.jar

# Expose the port your application runs on
EXPOSE 8080

# Specify the command to run your application
CMD ["java", "-jar", "app.jar"]
