# Use a base image with JDK, Maven, and Kafka installed
FROM maven:3-openjdk-17 AS build
WORKDIR /target

# Copy the Maven project file
COPY pom.xml .

# Download dependencies
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve

# Copy the application source code
COPY src ./src

# Build the application
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml clean package

# Use a lightweight base image with JRE, Kafka, and Zookeeper
FROM openjdk:17.0.1-jdk-slim 
RUN apt-get update && apt-get install -y wget \
    && wget -q https://downloads.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz \
    && tar -xzf kafka_2.13-3.0.0.tgz \
    && rm kafka_2.13-3.0.0.tgz
WORKDIR /kafka_2.13-3.0.0

# Copy Kafka configurations
COPY kafka.properties ./config/server.properties

# Set the working directory
WORKDIR /app

# Copy the packaged JAR file from the build stage
COPY --from=build app/target/Kafka-Backend.jar ./Kafka-Backend.jar

# Specify the command to run your application
ENTRYPOINT ["java", "-jar", "Kafka-Backend.jar"]